apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: prod
spec:
  containers:
    - name: con1
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: live
spec:
  containers:
    - name: con1
      image: nginx:1.14.2
      ports:
        - containerPort: 80
